### PR TITLE
FIX: add default argument for model_id

### PR DESCRIPTION
**Pull request by dmepham**

### CODE REVIEW

**Review by nkassis — COMMENTED** [review]
Just needs a test

**Comment by dmepham** [comment]
@nkassis 
```
============================================================================================================================= test session starts ==============================================================================================================================
platform linux -- Python 3.6.8, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /indicoio
collected 16 items                                                                                                                                                                                                                                                             

indicoio/api/tests/test_base.py::test_object_proxy_in PASSED
indicoio/api/tests/test_base.py::test_object_proxy_attrs PASSED
indicoio/api/tests/test_base.py::test_object_proxy_build PASSED
indicoio/api/tests/test_base.py::test_object_proxy_get PASSED
indicoio/client/tests/test_unit_serialization.py::test_deserialize_text PASSED
indicoio/client/tests/test_unit_serialization.py::test_deserialize_json PASSED
indicoio/client/tests/test_unit_serialization.py::test_deserialize_msgpack PASSED
indicoio/client/tests/test_unit_serialization.py::test_deserialize_unknown PASSED
tests/test_base_client.py::test_list_model_groups PASSED
tests/test_document_extraction.py::test_document_extraction_url PASSED
tests/test_document_extraction.py::test_document_extraction_file PASSED
tests/test_model_group.py::test_model_group_predict PASSED
tests/test_model_group.py::test_model_group_info PASSED
tests/test_model_group.py::test_model_group_load PASSED
tests/test_pdfextraction.py::test_pdf_extraction_url PASSED
tests/test_pdfextraction.py::test_pdf_extraction_file PASSED

============================================================================================================================= 16 passed in 48.40s ==============================================================================================================================
bash-4.4# 
```

**Comment by dmepham** [comment]
@nkassis or do you mean writing a new test? I just got the failing test to pass

**Review by sihrc — APPROVED** [review]

**Comment by sihrc** [comment]
Probably one that takes in model_id

**Review by nkassis — APPROVED** [review]

**Review by nkassis — APPROVED** [review]

**Review by sihrc — COMMENTED** [review]
Into development?

**Comment by dmepham** [comment]
into `master`. I don't see a development branch. I'm not sure of the strategy for merging changes in this repo, but I just kind of followed what the other PRs did.

I can bump the version to `2.0.1` and add a `CHANGELOG` if you guys think that's a good idea

**Comment by dmepham** [comment]
updated version to `2.0.1`

**Pull request merged**
